### ISSUE TITLE
転出証明書/転入届

### ISSUE THREAD

**Issue by pikatenor** [pikatenor/hikkoshi2019#13]
## 転出
[品川区 転出届](https://www.city.shinagawa.tokyo.jp/PC/shisetsu/shisetsu-kuyakusyo/shisetsu-kuyakusyo-chiiki/shisetsu-kuyakusyo-chiiki-eba1/index.html)
最寄り→[荏原第一地域センター](https://www.city.shinagawa.tokyo.jp/PC/shisetsu/shisetsu-kuyakusyo/shisetsu-kuyakusyo-chiiki/shisetsu-kuyakusyo-chiiki-eba1/index.html) 平日午前8時30分～午後5時

## 転入
[大田区 転入届](https://www.city.ota.tokyo.jp/seikatsu/koseki_j/jyuminhyo/todokede/tennyu.html)
たぶんここが近い→[千束特別出張所](https://www.city.ota.tokyo.jp/shisetsu/tokubetsushucchoujo/senzoku_tokubetsu.html) 平日午前8時30分から午後5時まで

**Comment by PONTA-N** [comment]
明文化されていないだけかもしれませんが、自治体での手続きが終わった後に会社へも変更届を出さないと住民税や年末調整がバグるので気をつけてください。
僕はそれでやらかしてめんどくさい事になりました。

**Comment by pikatenor** [comment]
I've got 転出証明書(valid from 12/7).

**Comment by pikatenor** [comment]
出した
