### ISSUE TITLE
インターネット

### ISSUE THREAD

**Issue by pikatenor** [pikatenor/hikkoshi2019#14]
#6 全てが未定

**Comment by flum1025** [comment]
新しいインターネット来るまでのつなぎのポケファイとかあるといいかも

**Comment by pikatenor** [comment]
「ニューロ光禁止」が賃貸契約の特約に明記されてて笑った（もともとフレッツ光系の予定なので別にいいんだが）

**Comment by pikatenor** [comment]
旧居閉鎖工事: 12/14 11:00
新居開通工事: 12/17 11:00

いずれも立ち会い不要っぽい

**Comment by pikatenor** [comment]
Try WiMAX 返却日: 12/18
Try UQ Mobile もやるか……

**Comment by pikatenor** [comment]
昨日ONUつないだらなんか使えたんで close
